### PR TITLE
#2: Remove `$` from method names

### PR DESCRIPTION
**Pull request by baldram**
Avoid using dollars in Scala identifiers to prevent compiler conflicts.

### CODE REVIEW

**Comment by baldram** [comment]
Additionally, I adjusted the .gitignore a bit because with the current implementation, a bunch of IntelliJ working files wanted to get added with the commit. Simply excluding the `.idea` directory should do it. Similarly, `.bsb` was not ignored at all. I didn't touch anything else, but the file contains items unrelated to this project, concerning other build tools not used by this project, etc. I left those as they were.

As for functional changes - in accordance with the agreements in the issue.

**Comment by rcardin** [comment]
Woah, man. Thanks! 🎉 I'll review the changes during the weekend.

**Comment by rcardin** [comment]
@baldram, do you have the time to update also the README file with the new names of the two methods?

If you don't, I'll take care of it 🫶

**Comment by baldram** [comment]
> @baldram, do you have the time to update also the README file with the new names of the two methods?

README.md is updated, did I overlook anything. I think any occurrence in the project is fixed.
Both `catching` and `asTry` have snipped in documentation and introduction. Or you mean adding more documentation above what was existing so far? Of course, I can do something more, but need a clarification what it would be or what did I overlook?

**Review by rcardin — APPROVED** [review]

**Comment by rcardin** [comment]
Sorry, I reviewed it from my iPhone 😅.

Approved 👌

**Comment by baldram** [comment]
I have no rights to merge it. If all fine, please feel free to merge. Thank you!

**Comment by rcardin** [comment]
@baldram, merged. Thanks a lot for the valuable contribution. If you have any other ideas to evolve the library, please feel free to open a new PR or to discuss it directly/

**Pull request merged**
